//
// ChatRoomsListBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatRoomsListBody: Codable {

    public var userId: String?

    public init(userId: String? = nil) {
        self.userId = userId
    }


}
