//
// ChatRoomParticipantsBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatRoomParticipantsBody: Codable {

    public var _id: String?
    public var chatRoomId: String?
    public var userId: String?

    public init(_id: String? = nil, chatRoomId: String? = nil, userId: String? = nil) {
        self._id = _id
        self.chatRoomId = chatRoomId
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case chatRoomId
        case userId
    }

}
