//
// ChatRoomParticipantsChatRooom.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatRoomParticipantsChatRooom: Codable {

    public var name: String?
    public var _description: String?
    public var company: ChatRoomParticipantsChatRooomCompany?

    public init(name: String? = nil, _description: String? = nil, company: ChatRoomParticipantsChatRooomCompany? = nil) {
        self.name = name
        self._description = _description
        self.company = company
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _description = "description"
        case company
    }

}
