//
// ChatRooms.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatRooms: Codable {

    public var _id: String?
    public var name: String?
    public var type: String?
    public var projectId: String?

    public init(_id: String? = nil, name: String? = nil, type: String? = nil, projectId: String? = nil) {
        self._id = _id
        self.name = name
        self.type = type
        self.projectId = projectId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case type
        case projectId
    }

}
