//
// ChatRooms.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatRooms: Codable {

    public var _id: String?
    public var name: String?
    public var type: String?
    public var projectName: String?
    public var companyName: String?
    public var imgUrl: String?
    public var latestMessage: String?
    public var latestMessageSendAt: String?

    public init(_id: String? = nil, name: String? = nil, type: String? = nil, projectName: String? = nil, companyName: String? = nil, imgUrl: String? = nil, latestMessage: String? = nil, latestMessageSendAt: String? = nil) {
        self._id = _id
        self.name = name
        self.type = type
        self.projectName = projectName
        self.companyName = companyName
        self.imgUrl = imgUrl
        self.latestMessage = latestMessage
        self.latestMessageSendAt = latestMessageSendAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case type
        case projectName
        case companyName
        case imgUrl
        case latestMessage
        case latestMessageSendAt
    }

}
