//
// ChatRoomParticipantsBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatRoomParticipantsBody: Codable {

    public var chatRooom: ChatRoomParticipantsChatRooom?

    public init(chatRooom: ChatRoomParticipantsChatRooom? = nil) {
        self.chatRooom = chatRooom
    }


}
