//
// Messages.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Messages: Codable {

    public var _id: String?
    public var userId: String?
    public var chatRoomId: String?
    public var text: String?

    public init(_id: String? = nil, userId: String? = nil, chatRoomId: String? = nil, text: String? = nil) {
        self._id = _id
        self.userId = userId
        self.chatRoomId = chatRoomId
        self.text = text
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userId
        case chatRoomId
        case text
    }

}
