//
// MessageBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MessageBody: Codable {

    public var userId: String?
    public var chatRoomId: String?
    public var text: String?
    public var sendAt: String?

    public init(userId: String? = nil, chatRoomId: String? = nil, text: String? = nil, sendAt: String? = nil) {
        self.userId = userId
        self.chatRoomId = chatRoomId
        self.text = text
        self.sendAt = sendAt
    }


}
