//
// MessagesGet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MessagesGet: Codable {

    public var _id: String?
    public var userName: String?
    public var text: String?
    public var imgUrl: String?
    public var sendAt: String?
    public var isMine: String?

    public init(_id: String? = nil, userName: String? = nil, text: String? = nil, imgUrl: String? = nil, sendAt: String? = nil, isMine: String? = nil) {
        self._id = _id
        self.userName = userName
        self.text = text
        self.imgUrl = imgUrl
        self.sendAt = sendAt
        self.isMine = isMine
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userName
        case text
        case imgUrl
        case sendAt
        case isMine
    }

}
