//
// Projects.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Projects: Codable {

    public var _id: String?
    public var companyId: String?
    public var name: String?
    public var _description: String?

    public init(_id: String? = nil, companyId: String? = nil, name: String? = nil, _description: String? = nil) {
        self._id = _id
        self.companyId = companyId
        self.name = name
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case companyId
        case name
        case _description = "description"
    }

}
