//
// Projects.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Projects: Codable {

    public var companyName: String?
    public var projectName: String?
    public var _description: String?
    public var testUrl: String?
    public var chatRoomId: String?

    public init(companyName: String? = nil, projectName: String? = nil, _description: String? = nil, testUrl: String? = nil, chatRoomId: String? = nil) {
        self.companyName = companyName
        self.projectName = projectName
        self._description = _description
        self.testUrl = testUrl
        self.chatRoomId = chatRoomId
    }

    public enum CodingKeys: String, CodingKey { 
        case companyName
        case projectName
        case _description = "description"
        case testUrl
        case chatRoomId
    }

}
