//
// Reviews.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Reviews: Codable {

    public var _id: String?
    public var sendAt: String?
    public var imgUrl: String?
    public var companyName: String?
    public var evaluationScore: Int?
    public var _description: String?

    public init(_id: String? = nil, sendAt: String? = nil, imgUrl: String? = nil, companyName: String? = nil, evaluationScore: Int? = nil, _description: String? = nil) {
        self._id = _id
        self.sendAt = sendAt
        self.imgUrl = imgUrl
        self.companyName = companyName
        self.evaluationScore = evaluationScore
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case sendAt
        case imgUrl
        case companyName
        case evaluationScore
        case _description = "description"
    }

}
