//
// Users.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Users: Codable {

    public var _id: String?
    public var displayName: String?
    public var apiKey: String?

    public init(_id: String? = nil, displayName: String? = nil, apiKey: String? = nil) {
        self._id = _id
        self.displayName = displayName
        self.apiKey = apiKey
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case displayName
        case apiKey
    }

}
