//
// ChatRoomParticipantsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ChatRoomParticipantsAPI {
    /**
     チャットルーム参加登録

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func postChatRoomParticipants(body: ChatRoomParticipantsBody, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        postChatRoomParticipantsWithRequestBuilder(body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     チャットルーム参加登録
     - POST /chat_room_participants

     - parameter body: (body)  

     - returns: RequestBuilder<Void> 
     */
    open class func postChatRoomParticipantsWithRequestBuilder(body: ChatRoomParticipantsBody) -> RequestBuilder<Void> {
        let path = "/chat_room_participants"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
