//
// ChatRoomsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ChatRoomsAPI {
    /**
     チャットルーム情報取得

     - parameter projectId: (query)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getChatRooms(projectId: String, completion: @escaping ((_ data: [ChatRooms]?,_ error: Error?) -> Void)) {
        getChatRoomsWithRequestBuilder(projectId: projectId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     チャットルーム情報取得
     - GET /chat_room

     - examples: [{contentType=application/json, example=[ {
  "name" : "name",
  "id" : "id",
  "type" : "type",
  "projectId" : "projectId"
}, {
  "name" : "name",
  "id" : "id",
  "type" : "type",
  "projectId" : "projectId"
} ]}]
     - parameter projectId: (query)  

     - returns: RequestBuilder<[ChatRooms]> 
     */
    open class func getChatRoomsWithRequestBuilder(projectId: String) -> RequestBuilder<[ChatRooms]> {
        let path = "/chat_room"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "projectId": projectId
        ])


        let requestBuilder: RequestBuilder<[ChatRooms]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
