//
// HelloAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class HelloAPI {
    /**
     テストAPI

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func hello(completion: @escaping ((_ data: InlineResponse2002?,_ error: Error?) -> Void)) {
        helloWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     テストAPI
     - GET /hello

     - examples: [{contentType=application/json, example={
  "message" : "message"
}}]

     - returns: RequestBuilder<InlineResponse2002> 
     */
    open class func helloWithRequestBuilder() -> RequestBuilder<InlineResponse2002> {
        let path = "/hello"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<InlineResponse2002>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
