//
// MessagesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class MessagesAPI {
    /**
     メッセージ一覧取得

     - parameter chatRoomId: (query)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMessages(chatRoomId: String, completion: @escaping ((_ data: [MessagesGet]?,_ error: Error?) -> Void)) {
        getMessagesWithRequestBuilder(chatRoomId: chatRoomId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     メッセージ一覧取得
     - GET /messages

     - examples: [{contentType=application/json, example=[ {
  "chatRoomId" : "chatRoomId",
  "id" : "id",
  "text" : "text",
  "userId" : "userId"
}, {
  "chatRoomId" : "chatRoomId",
  "id" : "id",
  "text" : "text",
  "userId" : "userId"
} ]}]
     - parameter chatRoomId: (query)  

     - returns: RequestBuilder<[MessagesGet]> 
     */
    open class func getMessagesWithRequestBuilder(chatRoomId: String) -> RequestBuilder<[MessagesGet]> {
        let path = "/messages"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "chatRoomId": chatRoomId
        ])


        let requestBuilder: RequestBuilder<[MessagesGet]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
