//
// MessagesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class MessagesAPI {
    /**
     メッセージ一覧取得

     - parameter chatRoomId: (query)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMessages(chatRoomId: String, completion: @escaping ((_ data: [Messages]?,_ error: Error?) -> Void)) {
        getMessagesWithRequestBuilder(chatRoomId: chatRoomId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     メッセージ一覧取得
     - GET /messages

     - examples: [{contentType=application/json, example=[ {
  "chatRoomId" : "chatRoomId",
  "id" : "id",
  "text" : "text",
  "userId" : "userId"
}, {
  "chatRoomId" : "chatRoomId",
  "id" : "id",
  "text" : "text",
  "userId" : "userId"
} ]}]
     - parameter chatRoomId: (query)  

     - returns: RequestBuilder<[Messages]> 
     */
    open class func getMessagesWithRequestBuilder(chatRoomId: String) -> RequestBuilder<[Messages]> {
        let path = "/messages"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "chatRoomId": chatRoomId
        ])


        let requestBuilder: RequestBuilder<[Messages]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     メッセージ投稿

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func postMessage(body: MessageBody, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        postMessageWithRequestBuilder(body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     メッセージ投稿
     - POST /message

     - parameter body: (body)  

     - returns: RequestBuilder<Void> 
     */
    open class func postMessageWithRequestBuilder(body: MessageBody) -> RequestBuilder<Void> {
        let path = "/message"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
