//
// ProjectsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ProjectsAPI {
    /**
     プロジェクト一覧取得

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getProjects(completion: @escaping ((_ data: [InlineResponse200]?,_ error: Error?) -> Void)) {
        getProjectsWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     プロジェクト一覧取得
     - GET /projects/list

     - examples: [{contentType=application/json, example=[ {
  "name" : "name",
  "description" : "description",
  "company" : {
    "name" : "name",
    "id" : "id"
  },
  "id" : "id"
}, {
  "name" : "name",
  "description" : "description",
  "company" : {
    "name" : "name",
    "id" : "id"
  },
  "id" : "id"
} ]}]

     - returns: RequestBuilder<[InlineResponse200]> 
     */
    open class func getProjectsWithRequestBuilder() -> RequestBuilder<[InlineResponse200]> {
        let path = "/projects/list"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[InlineResponse200]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
